apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: liulizhilu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: ConnectionStrings__Database
          value: "Host=postgres;Port=5432;Database=LiuliZhiluDB;Username=postgres;Password=postgres"
